version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.18.1 
    steps:
      - run:
          name: The First Step
          command: |
            checkout
            npm i
            npm test
